### ISSUE TITLE
Order of input in .py file

### ISSUE THREAD

**Issue by mohataher** [amcmorl/MadgwickAHRS_python#1]
It seems like you have a missing order of the input in you .py file. 

```python
MadgwickAHRS.MadgwickAHRSupdate(ax, ay, az, gx, gy, gz, mx, my, mz)
```

Shouldn't gyro data come first?

**Comment by amcmorl** [comment]
Yes, you're right. I had corrected in my local copy. Will update from there soon. Thanks for pointing out the issue.
